[Refactor] Birthday
BirthdayyBot/BirthdayyBot pull request #102
Opened 2023-03-16 15:03 UTC by swiizyy

### Refactor
- Move all the functions used by the BirthdayReminder into its class
- Refactor generateEmbed & add ApiEmbed type

### Fix
- Fix EmbedInformationModel

### Todo

- [ ] Add listener to track progress of Birthday Reminder Task

2023-03-16 21:33 UTC, nikolaischunk commented on src/commands/general/birthday.ts
> +			await BirthdayReminderTask.prototype.birthdayEvent(guild_id, user_id, true);
what is this protoype for? looks wierd

2023-03-16 22:09 UTC, nikolaischunk approved these changes

2023-03-16 23:14 UTC, nikolaischunk requested changes
Have you ever built the application with these changes? Its giving me a lot of errors, please resolve them before merging.

2023-03-17 01:46 UTC, Swiizyy commented
Sucess check build/lint 🎆

2023-03-17 09:03 UTC, nikolaischunk approved these changes

2023-03-17 09:03 UTC, merged